/* CS 225 - Fundamentals of Computer Science
 * File Name: Ball.java
 * Java Programming
 * Project 4 - Due 03/20/2015
 * Instructor: Dan Grissom
 * 
 * Name 1: Monica Bebawy
 * Description: This file contains the source code for the
 * Ball class, which mostly just contains a number of variables
 * which describe the balls position and orientation in space.
 */
//////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DO NOT EDIT THIS FILE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
//////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////

public abstract class Ball
{
	protected double ballCenterX;		// The ball's x position (in pixels) on the court
	protected double ballCenterY;		// The ball's y position (in pixels) on the court
	protected double radius;			// The ball's radius
	protected double xVelocity;			// The ball's horizontal velocity, in pixels-per-frame
	protected double yVelocity;			// The ball's horizontal velocity, in pixels-per-frame
	protected double degreesRotated;	// The ball's rotation, in degrees
	protected double bounceSpeedLoss;	// The percentage of speed (0-1) which the ball instantly loses when hitting ground
	protected boolean ballStillBouncing;// Tells whether ball is still bouncing
	private String ballImageName;		// String which holds image name representing the ball
	
	//////////////////////////////////////////////////////////
	// Constructor
	Ball(double rad, double bsl,  String imageNameWithExt)
	{
		ballCenterX = 0;
		ballCenterY = 0;
		degreesRotated = 0;
		ballStillBouncing = false;
		
		radius = rad;
		bounceSpeedLoss = bsl;
		ballImageName = imageNameWithExt;
	}
	
	//////////////////////////////////////////////////////////
	// Getters (for the Court class to use)
	public String getBallImageName()
	{
		return ballImageName;
	}
	
	public double getRadius()
	{
		return radius;
	}
	
	public double getBallCenterX()
	{
		return ballCenterX;
	}
	
	public double getBallCenterY()
	{
		return ballCenterY;
	}
	
	public double getDegreesRotated()
	{
		return degreesRotated;
	}
	
	public double getBounceSpeedLoss()
	{
		return bounceSpeedLoss;
	}
}
